name: RDP Access via Getscreen.me on macOS Runner

on:
  workflow_dispatch:

jobs:
  rdp-macos:
    runs-on: macos-latest
    timeout-minutes: 300 # 5 hours

    steps:
      - name: Set up keep-alive hack
        run: |
          nohup bash -c 'while true; do echo "keepalive"; sleep 60; done' &

      - name: Download Getscreen.me DMG
        run: |
          curl -L --retry 3 -o Getscreen.me.dmg "https://getscreen.me/download/Getscreen.me.dmg"
          file Getscreen.me.dmg
          ls -lh Getscreen.me.dmg

      - name: Attempt to mount Getscreen.me.dmg
        run: |
          hdiutil attach Getscreen.me.dmg || echo "Mount failed, attempting to unzip"
          unzip -q Getscreen.me.dmg || echo "Unzip also failed"

      - name: List contents of /Volumes and current directory
        run: |
          ls /Volumes || true
          ls -lah

      - name: Attempt to run Getscreen.me.app if found
        run: |
          if [ -d "/Volumes/Getscreen.me/Getscreen.me.app" ]; then
            cp -R "/Volumes/Getscreen.me/Getscreen.me.app" .
            open "./Getscreen.me.app"
            sleep 60
          elif [ -d "./Getscreen.me.app" ]; then
            open "./Getscreen.me.app"
            sleep 60
          else
            echo "Getscreen.me.app not found, please check the DMG/ZIP format."
          fi

      - name: Keep job alive for 5 hours
        run: |
          echo "RDP session started. Workflow will keep running for 5 hours."
          sleep $((5 * 60 * 60))
